//! Cookie jar implementation for storing MAM cookies
const std = @import("std");
const Allocator = std.mem.Allocator;
const Io = std.Io;
const zeit = @import("zeit");

const CookieJar = @This();

const PATH = "MAM.cookies";

const FILE_HEADER =
    \\# Netscape HTTP Cookie File
    \\# https://curl.se/docs/http-cookies.html
    \\# This file was generated by mam-point-spender! Edit at your own risk.
;

pub const Cookie = struct {
    domain: []const u8,
    include_subdomains: bool,
    path: []const u8,
    secure: bool,
    expires_at: i64,
    name: []const u8,
    value: []const u8,

    pub const ParseError = error{
        InvalidFormat,
    } || std.fmt.ParseIntError;

    fn parseLine(line: []const u8) ParseError!Cookie {
        var parts = std.mem.splitScalar(u8, line, '\t');

        return .{
            .domain = parts.next() orelse return error.InvalidFormat,
            .include_subdomains = std.mem.eql(u8, parts.next() orelse return error.InvalidFormat, "TRUE"),
            .path = parts.next() orelse return error.InvalidFormat,
            .secure = std.mem.eql(u8, parts.next() orelse return error.InvalidFormat, "TRUE"),
            .expires_at = try std.fmt.parseInt(i64, parts.next() orelse return error.InvalidFormat, 10),
            .name = parts.next() orelse return error.InvalidFormat,
            .value = parts.next() orelse return error.InvalidFormat,
        };
    }

    // Serialize the cookie back to a line format suitable for writing to the file
    // Does not include a newline character, the caller should handle that
    fn toLine(self: Cookie, writer: *std.Io.Writer) Io.Writer.Error!void {
        const secure_str = if (self.secure) "TRUE" else "FALSE";
        const include_subdomains_str = if (self.include_subdomains) "TRUE" else "FALSE";
        try writer.print("{s}\t{s}\t{s}\t{s}\t{d}\t{s}\t{s}", .{ self.domain, include_subdomains_str, self.path, secure_str, self.expires_at, self.name, self.value });
    }

    pub fn isExpired(self: Cookie, io: Io) bool {
        if (self.expires_at == 0) return false;
        const now = Io.Clock.real.now(io).toSeconds();
        return self.expires_at < now;
    }
};

arena: std.heap.ArenaAllocator,
cookies: std.ArrayListUnmanaged(Cookie) = .empty,

pub fn init(allocator: Allocator) CookieJar {
    return .{ .arena = std.heap.ArenaAllocator.init(allocator) };
}

pub fn deinit(self: *CookieJar) void {
    self.arena.deinit();
}

// Reads cookies from the file, replacing any existing cookies in the jar.
// If the file does not exist, this will just leave the jar empty.
// If the file is malformed, this will return an error.
pub fn readFile(self: *CookieJar, io: Io) !void {
    self.cookies.clearAndFree(self.arena.allocator());
    _ = self.arena.reset(.retain_capacity);

    var file = Io.Dir.cwd().openFile(io, PATH, .{
        .mode = .read_only,
        .allow_directory = false,
    }) catch |err| switch (err) {
        Io.File.OpenError.FileNotFound => return, // No cookie file, just start with an empty jar
        else => return err,
    };
    defer file.close(io);

    var buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &buffer);
    const r = &file_reader.interface;

    while (true) {
        const line = try r.takeDelimiter('\n') orelse break;
        if (line.len == 0) continue;
        if (line[0] == '#') continue; // Skip comments

        const cookie = try Cookie.parseLine(try self.arena.allocator().dupe(u8, line));
        try self.cookies.append(self.arena.allocator(), cookie);
    }
}

pub const WriteFileError = Io.Dir.CreateFileAtomicError || Io.Writer.Error || Io.File.Atomic.ReplaceError;

// Writes the current cookies to the file, replacing any existing file.
// This will create the file if it does not exist, and will overwrite it if it does.
// If there is an error writing the file, this will return an error and the existing file will remain unchanged.
pub fn writeFile(self: *const CookieJar, io: Io) WriteFileError!void {
    var af = try Io.Dir.cwd().createFileAtomic(io, PATH, .{ .replace = true });
    defer af.deinit(io);

    var buf: [4096]u8 = undefined;
    var writer = af.file.writer(io, &buf);
    const w = &writer.interface;

    try w.writeAll(FILE_HEADER);
    try w.writeByte('\n');

    for (self.cookies.items) |cookie| {
        // TODO: Skip expired cookies
        try cookie.toLine(w);
        try w.writeByte('\n');
    }

    try w.flush();
    try af.replace(io);
}

pub const CookieHeaderError = Allocator.Error || std.Uri.GetHostError;

// Generates a Cookie header value for the given URI, including all cookies that match the URI's domain and path, and are not expired.
pub fn cookieHeader(self: *const CookieJar, gpa: Allocator, io: Io, uri: std.Uri) CookieHeaderError![]const u8 {
    var header = std.ArrayList(u8).empty;
    defer header.deinit(gpa);

    var host_buffer: [255]u8 = undefined;
    const host = try uri.getHost(&host_buffer);

    var writer = Io.Writer.Allocating.init(gpa);
    // Writer can only fail if we run out of memory, so we can treat it as an OOM error
    uri.path.formatPath(&writer.writer) catch return Allocator.Error.OutOfMemory;
    const path = try writer.toOwnedSlice();
    defer gpa.free(path);

    const now = Io.Clock.real.now(io).toSeconds();
    for (self.cookies.items) |cookie| {
        if (cookie.expires_at < now and cookie.expires_at != 0) continue; // Skip expired cookies, but allow session cookies
        // TODO: handle domain matching properly
        if (!std.mem.endsWith(u8, host.bytes, cookie.domain)) continue; // Domain does not match
        if (!cookie.include_subdomains and !std.mem.eql(u8, host.bytes, cookie.domain)) continue; // Subdomain does not match
        if (!std.mem.startsWith(u8, path, cookie.path)) continue; // Path does not match
        if (cookie.secure and !std.mem.eql(u8, uri.scheme, "https")) continue; // Secure cookie, but not HTTPS

        if (header.items.len > 0) {
            try header.appendSlice(gpa, "; ");
        }
        try header.appendSlice(gpa, cookie.name);
        try header.append(gpa, '=');
        try header.appendSlice(gpa, cookie.value);
    }

    return header.toOwnedSlice(gpa);
}

const AttributeField = enum {
    Domain,
    Expires,
    MaxAge,
    Path,
    Secure,

    const map = std.StaticStringMap(AttributeField).initComptime(.{
        .{ "domain", .Domain },
        .{ "expires", .Expires },
        .{ "max-age", .MaxAge },
        .{ "path", .Path },
        .{ "secure", .Secure },
    });
};

pub const AddCookieError = Allocator.Error || std.Uri.GetHostAllocError || error{
    InvalidFormat,
};

// Parses a Set-Cookie header value and adds the cookie to the jar.
// This will overwrite existing cookies with the same name/domain/path.
pub fn addCookie(self: *CookieJar, io: Io, uri: std.Uri, header: []const u8) AddCookieError!void {
    // Duplicate the header string so we use it.
    const h = try self.arena.allocator().dupe(u8, header);

    // Split the header into parts by ';'
    var parts = std.mem.splitScalar(u8, h, ';');

    // Extract name and value from the first part
    var name_value = std.mem.splitScalar(u8, parts.next() orelse return error.InvalidFormat, '=');
    const name = name_value.next() orelse return error.InvalidFormat;
    const value = name_value.next() orelse return error.InvalidFormat;

    // Default cookie values
    const host = try uri.getHostAlloc(self.arena.allocator());
    var cookie: Cookie = .{
        .domain = host.bytes,
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = 0, // Session cookie by default
        .name = name,
        .value = value,
    };

    // Parse attributes
    while (parts.next()) |part| {
        var attrs = std.mem.splitScalar(u8, part, '=');

        var buffer: [32]u8 = undefined;
        const keyOrig = std.mem.trim(u8, attrs.next() orelse continue, " ");
        const key = std.ascii.lowerString(&buffer, keyOrig[0..@min(keyOrig.len, buffer.len)]);

        const val = std.mem.trim(u8, attrs.next() orelse "", " ");

        const attr = AttributeField.map.get(key) orelse continue; // Ignore unknown attributes
        switch (attr) {
            .Domain => {
                cookie.domain = val;
                cookie.include_subdomains = true;
            },
            .Expires => {
                if (cookie.expires_at != 0) continue; // Max-Age takes precedence over Expires, so ignore Expires if Max-Age is already set
                const instant = zeit.instantFromText(.rfc1123, val, &zeit.utc) catch return error.InvalidFormat;
                cookie.expires_at = instant.unixTimestamp();
            },
            .MaxAge => {
                const max_age = std.fmt.parseInt(i64, val, 10) catch return error.InvalidFormat;
                if (max_age <= 0) {
                    // Cookie expires immediately, so we can skip adding it to the jar
                    return;
                }
                const now = Io.Clock.real.now(io).toSeconds();
                cookie.expires_at = now + max_age;
            },
            .Path => {
                cookie.path = val;
            },
            .Secure => {
                cookie.secure = true;
            },
        }
    }

    // De-dupe the cookie by removing any existing cookie with the same name/domain/path
    for (0..self.cookies.items.len) |i| {
        if (std.mem.eql(u8, self.cookies.items[i].name, cookie.name) and
            std.mem.eql(u8, self.cookies.items[i].domain, cookie.domain) and
            std.mem.eql(u8, self.cookies.items[i].path, cookie.path))
        {
            _ = self.cookies.orderedRemove(i);
            break;
        }
    }

    try self.cookies.append(self.arena.allocator(), cookie);
}

test "addCookie" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/path");
    try jar.addCookie(std.testing.io, uri, "sessionId=abc123; Path=/v1; Secure");
    try jar.addCookie(std.testing.io, uri, "theme=light; Expires=Wed, 09 Jun 2021 10:18:14 GMT");

    try std.testing.expectEqual(jar.cookies.items.len, 2);
    try std.testing.expectEqualStrings(jar.cookies.items[0].name, "sessionId");
    try std.testing.expectEqualStrings(jar.cookies.items[0].value, "abc123");
    try std.testing.expectEqualStrings(jar.cookies.items[0].path, "/v1");
    try std.testing.expect(jar.cookies.items[0].secure);
    try std.testing.expectEqualStrings(jar.cookies.items[1].name, "theme");
    try std.testing.expectEqualStrings(jar.cookies.items[1].value, "light");
    try std.testing.expectEqualStrings(jar.cookies.items[1].path, "/");
    try std.testing.expect(!jar.cookies.items[1].secure);
    try std.testing.expectEqual(jar.cookies.items[1].expires_at, 1623233894);
}

test "cookieHeader" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/path");
    try jar.addCookie(std.testing.io, uri, "sessionId=abc123; Path=/path; Secure");
    try jar.addCookie(std.testing.io, uri, "sessionId2=abc123; Path=/v1; Secure");
    try jar.addCookie(std.testing.io, uri, "theme=light; Max-Age=3600");
    try jar.addCookie(std.testing.io, uri, "theme2=light; Expires=Wed, 09 Jun 2021 10:18:14 GMT");

    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings(header, "sessionId=abc123; theme=light");
}

test "Cookie.parseLine parses a well-formed Netscape cookie line" {
    const line = "example.com\tTRUE\t/\tFALSE\t1700000000\tsession\txyz";
    const cookie = try Cookie.parseLine(line);

    try std.testing.expectEqualStrings("example.com", cookie.domain);
    try std.testing.expect(cookie.include_subdomains);
    try std.testing.expectEqualStrings("/", cookie.path);
    try std.testing.expect(!cookie.secure);
    try std.testing.expectEqual(@as(i64, 1700000000), cookie.expires_at);
    try std.testing.expectEqualStrings("session", cookie.name);
    try std.testing.expectEqualStrings("xyz", cookie.value);
}

test "Cookie.parseLine treats non-TRUE flag values as false" {
    const line = "example.com\tFALSE\t/path\tTRUE\t0\tname\tvalue";
    const cookie = try Cookie.parseLine(line);

    try std.testing.expect(!cookie.include_subdomains);
    try std.testing.expect(cookie.secure);
    try std.testing.expectEqual(@as(i64, 0), cookie.expires_at);
    try std.testing.expectEqualStrings("/path", cookie.path);
}

test "Cookie.parseLine returns InvalidFormat for missing fields" {
    const line = "example.com\tTRUE\t/\tFALSE\t1700000000\tsession";
    try std.testing.expectError(error.InvalidFormat, Cookie.parseLine(line));
}

test "Cookie.parseLine returns parse error for non-numeric expires" {
    const line = "example.com\tTRUE\t/\tFALSE\tnot-a-number\tsession\txyz";
    try std.testing.expectError(error.InvalidCharacter, Cookie.parseLine(line));
}

test "Cookie.toLine round trips through parseLine" {
    const original: Cookie = .{
        .domain = ".example.com",
        .include_subdomains = true,
        .path = "/api",
        .secure = true,
        .expires_at = 1234567890,
        .name = "auth",
        .value = "token-value",
    };

    var writer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer writer.deinit();
    try original.toLine(&writer.writer);

    const serialized = writer.written();
    try std.testing.expectEqualStrings(
        ".example.com\tTRUE\t/api\tTRUE\t1234567890\tauth\ttoken-value",
        serialized,
    );

    const parsed = try Cookie.parseLine(serialized);
    try std.testing.expectEqualStrings(original.domain, parsed.domain);
    try std.testing.expectEqual(original.include_subdomains, parsed.include_subdomains);
    try std.testing.expectEqualStrings(original.path, parsed.path);
    try std.testing.expectEqual(original.secure, parsed.secure);
    try std.testing.expectEqual(original.expires_at, parsed.expires_at);
    try std.testing.expectEqualStrings(original.name, parsed.name);
    try std.testing.expectEqualStrings(original.value, parsed.value);
}

test "Cookie.toLine writes FALSE flags correctly" {
    const cookie: Cookie = .{
        .domain = "example.com",
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = 0,
        .name = "n",
        .value = "v",
    };

    var writer: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer writer.deinit();
    try cookie.toLine(&writer.writer);
    try std.testing.expectEqualStrings(
        "example.com\tFALSE\t/\tFALSE\t0\tn\tv",
        writer.written(),
    );
}

test "Cookie.isExpired treats expires_at == 0 as a session cookie" {
    const cookie: Cookie = .{
        .domain = "example.com",
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = 0,
        .name = "n",
        .value = "v",
    };
    try std.testing.expect(!cookie.isExpired(std.testing.io));
}

test "Cookie.isExpired returns true for past timestamps" {
    const cookie: Cookie = .{
        .domain = "example.com",
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = 1,
        .name = "n",
        .value = "v",
    };
    try std.testing.expect(cookie.isExpired(std.testing.io));
}

test "Cookie.isExpired returns false for far-future timestamps" {
    const cookie: Cookie = .{
        .domain = "example.com",
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = std.math.maxInt(i64),
        .name = "n",
        .value = "v",
    };
    try std.testing.expect(!cookie.isExpired(std.testing.io));
}

test "addCookie defaults to URI host without subdomain matching" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "a=1");

    try std.testing.expectEqual(@as(usize, 1), jar.cookies.items.len);
    try std.testing.expectEqualStrings("example.com", jar.cookies.items[0].domain);
    try std.testing.expect(!jar.cookies.items[0].include_subdomains);
    try std.testing.expectEqualStrings("/", jar.cookies.items[0].path);
    try std.testing.expect(!jar.cookies.items[0].secure);
    try std.testing.expectEqual(@as(i64, 0), jar.cookies.items[0].expires_at);
}

test "addCookie with Domain attribute enables subdomain matching" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "a=1; Domain=.example.com");

    try std.testing.expectEqualStrings(".example.com", jar.cookies.items[0].domain);
    try std.testing.expect(jar.cookies.items[0].include_subdomains);
}

test "addCookie Max-Age <= 0 skips the cookie" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "expired=1; Max-Age=0");
    try jar.addCookie(std.testing.io, uri, "expired2=1; Max-Age=-5");

    try std.testing.expectEqual(@as(usize, 0), jar.cookies.items.len);
}

test "addCookie Max-Age sets a future expiry" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "a=1; Max-Age=3600");

    const now = std.Io.Clock.real.now(std.testing.io).toSeconds();
    const expires = jar.cookies.items[0].expires_at;
    try std.testing.expect(expires > now);
    try std.testing.expect(expires <= now + 3600);
}

test "addCookie Max-Age wins over Expires regardless of order" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "a=1; Max-Age=3600; Expires=Wed, 09 Jun 2021 10:18:14 GMT");
    try jar.addCookie(std.testing.io, uri, "b=1; Expires=Wed, 09 Jun 2021 10:18:14 GMT; Max-Age=3600");

    const now = std.Io.Clock.real.now(std.testing.io).toSeconds();
    for (jar.cookies.items) |c| {
        try std.testing.expect(c.expires_at > now);
    }
}

test "addCookie replaces an existing cookie with the same name/domain/path" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "session=old");
    try jar.addCookie(std.testing.io, uri, "session=new");

    try std.testing.expectEqual(@as(usize, 1), jar.cookies.items.len);
    try std.testing.expectEqualStrings("new", jar.cookies.items[0].value);
}

test "addCookie keeps cookies with the same name but different path" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "session=root; Path=/");
    try jar.addCookie(std.testing.io, uri, "session=api; Path=/api");

    try std.testing.expectEqual(@as(usize, 2), jar.cookies.items.len);
}

test "addCookie returns InvalidFormat for a malformed header" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try std.testing.expectError(error.InvalidFormat, jar.addCookie(std.testing.io, uri, "no-equals-sign"));
}

test "addCookie ignores unknown attributes" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "a=1; HttpOnly; SameSite=Lax");

    try std.testing.expectEqual(@as(usize, 1), jar.cookies.items.len);
    try std.testing.expectEqualStrings("1", jar.cookies.items[0].value);
}

test "cookieHeader omits secure cookies over plain HTTP" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const https_uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, https_uri, "session=secret; Secure");
    try jar.addCookie(std.testing.io, https_uri, "theme=light");

    const http_uri = try std.Uri.parse("http://example.com/");
    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, http_uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings("theme=light", header);
}

test "cookieHeader omits expired cookies but keeps session cookies" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, uri, "session=keep");
    try jar.addCookie(std.testing.io, uri, "stale=gone; Expires=Wed, 09 Jun 2021 10:18:14 GMT");

    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings("session=keep", header);
}

test "cookieHeader omits cookies whose domain does not match" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const example_uri = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, example_uri, "a=1");

    const other_uri = try std.Uri.parse("https://other.com/");
    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, other_uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings("", header);
}

test "cookieHeader omits cookies whose path does not match" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const set_uri = try std.Uri.parse("https://example.com/api");
    try jar.addCookie(std.testing.io, set_uri, "a=1; Path=/api");

    const root_uri = try std.Uri.parse("https://example.com/");
    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, root_uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings("", header);
}

test "cookieHeader applies subdomain rules from Domain attribute" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const apex = try std.Uri.parse("https://example.com/");
    try jar.addCookie(std.testing.io, apex, "shared=1; Domain=.example.com");
    try jar.addCookie(std.testing.io, apex, "apex_only=1");

    const sub_uri = try std.Uri.parse("https://api.example.com/");
    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, sub_uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings("shared=1", header);
}
