//! Cookie jar implementation for storing MAM cookies
const std = @import("std");
const Allocator = std.mem.Allocator;
const Io = std.Io;
const zeit = @import("zeit");

const CookieJar = @This();

const PATH = "MAM.cookies";

const FILE_HEADER =
    \\# Netscape HTTP Cookie File
    \\# https://curl.se/docs/http-cookies.html
    \\# This file was generated by mam-point-spender! Edit at your own risk.
;

pub const Cookie = struct {
    domain: []const u8,
    include_subdomains: bool,
    path: []const u8,
    secure: bool,
    expires_at: i64,
    name: []const u8,
    value: []const u8,

    pub const ParseError = error{
        InvalidFormat,
    } || std.fmt.ParseIntError;

    fn parseLine(line: []const u8) ParseError!Cookie {
        var parts = std.mem.splitScalar(u8, line, '\t');

        return .{
            .domain = parts.next() orelse return error.InvalidFormat,
            .include_subdomains = std.mem.eql(u8, parts.next() orelse return error.InvalidFormat, "TRUE"),
            .path = parts.next() orelse return error.InvalidFormat,
            .secure = std.mem.eql(u8, parts.next() orelse return error.InvalidFormat, "TRUE"),
            .expires_at = try std.fmt.parseInt(i64, parts.next() orelse return error.InvalidFormat, 10),
            .name = parts.next() orelse return error.InvalidFormat,
            .value = parts.next() orelse return error.InvalidFormat,
        };
    }

    // Serialize the cookie back to a line format suitable for writing to the file
    // Does not include a newline character, the caller should handle that
    fn toLine(self: Cookie, writer: *std.Io.Writer) Io.Writer.Error!void {
        const secure_str = if (self.secure) "TRUE" else "FALSE";
        const include_subdomains_str = if (self.include_subdomains) "TRUE" else "FALSE";
        try writer.print("{s}\t{s}\t{s}\t{s}\t{d}\t{s}\t{s}", .{ self.domain, include_subdomains_str, self.path, secure_str, self.expires_at, self.name, self.value });
    }

    pub fn isExpired(self: Cookie, io: Io) bool {
        if (self.expires_at == 0) return false;
        const now = Io.Clock.real.now(io).toSeconds();
        return self.expires_at < now;
    }
};

arena: std.heap.ArenaAllocator,
cookies: std.ArrayListUnmanaged(Cookie) = .empty,

pub fn init(allocator: Allocator) CookieJar {
    return .{ .arena = std.heap.ArenaAllocator.init(allocator) };
}

pub fn deinit(self: *CookieJar) void {
    self.arena.deinit();
}

// Reads cookies from the file, replacing any existing cookies in the jar.
// If the file does not exist, this will just leave the jar empty.
// If the file is malformed, this will return an error.
pub fn readFile(self: *CookieJar, io: Io) !void {
    self.cookies.clearAndFree(self.arena.allocator());
    _ = self.arena.reset(.retain_capacity);

    var file = Io.Dir.cwd().openFile(io, PATH, .{
        .mode = .read_only,
        .allow_directory = false,
    }) catch |err| switch (err) {
        Io.File.OpenError.FileNotFound => return, // No cookie file, just start with an empty jar
        else => return err,
    };
    defer file.close(io);

    var buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &buffer);
    const r = &file_reader.interface;

    while (true) {
        const line = try r.takeDelimiter('\n') orelse break;
        if (line.len == 0) continue;
        if (line[0] == '#') continue; // Skip comments

        const cookie = try Cookie.parseLine(try self.arena.allocator().dupe(u8, line));
        try self.cookies.append(self.arena.allocator(), cookie);
    }
}

pub const WriteFileError = Io.Dir.CreateFileAtomicError || Io.Writer.Error || Io.File.Atomic.ReplaceError;

// Writes the current cookies to the file, replacing any existing file.
// This will create the file if it does not exist, and will overwrite it if it does.
// If there is an error writing the file, this will return an error and the existing file will remain unchanged.
pub fn writeFile(self: *const CookieJar, io: Io) WriteFileError!void {
    var af = try Io.Dir.cwd().createFileAtomic(io, PATH, .{ .replace = true });
    defer af.deinit(io);

    var buf: [4096]u8 = undefined;
    var writer = af.file.writer(io, &buf);
    const w = &writer.interface;

    try w.writeAll(FILE_HEADER);
    try w.writeByte('\n');

    for (self.cookies.items) |cookie| {
        // TODO: Skip expired cookies
        try cookie.toLine(w);
        try w.writeByte('\n');
    }

    try w.flush();
    try af.replace(io);
}

pub const CookieHeaderError = Allocator.Error || std.Uri.GetHostError;

// Generates a Cookie header value for the given URI, including all cookies that match the URI's domain and path, and are not expired.
pub fn cookieHeader(self: *const CookieJar, gpa: Allocator, io: Io, uri: std.Uri) CookieHeaderError![]const u8 {
    var header = std.ArrayList(u8).empty;
    defer header.deinit(gpa);

    var host_buffer: [255]u8 = undefined;
    const host = try uri.getHost(&host_buffer);

    var writer = Io.Writer.Allocating.init(gpa);
    // Writer can only fail if we run out of memory, so we can treat it as an OOM error
    uri.path.formatPath(&writer.writer) catch return Allocator.Error.OutOfMemory;
    const path = try writer.toOwnedSlice();
    defer gpa.free(path);

    const now = Io.Clock.real.now(io).toSeconds();
    for (self.cookies.items) |cookie| {
        if (cookie.expires_at < now and cookie.expires_at != 0) continue; // Skip expired cookies, but allow session cookies
        // TODO: handle domain matching properly
        if (!std.mem.endsWith(u8, host.bytes, cookie.domain)) continue; // Domain does not match
        if (!cookie.include_subdomains and !std.mem.eql(u8, host.bytes, cookie.domain)) continue; // Subdomain does not match
        if (!std.mem.startsWith(u8, path, cookie.path)) continue; // Path does not match
        if (cookie.secure and !std.mem.eql(u8, uri.scheme, "https")) continue; // Secure cookie, but not HTTPS

        if (header.items.len > 0) {
            try header.appendSlice(gpa, "; ");
        }
        try header.appendSlice(gpa, cookie.name);
        try header.append(gpa, '=');
        try header.appendSlice(gpa, cookie.value);
    }

    return header.toOwnedSlice(gpa);
}

const AttributeField = enum {
    Domain,
    Expires,
    MaxAge,
    Path,
    Secure,

    const map = std.StaticStringMap(AttributeField).initComptime(.{
        .{ "domain", .Domain },
        .{ "expires", .Expires },
        .{ "max-age", .MaxAge },
        .{ "path", .Path },
        .{ "secure", .Secure },
    });
};

pub const AddCookieError = Allocator.Error || std.Uri.GetHostAllocError || error{
    InvalidFormat,
};

// Parses a Set-Cookie header value and adds the cookie to the jar.
// This will overwrite existing cookies with the same name/domain/path.
pub fn addCookie(self: *CookieJar, io: Io, uri: std.Uri, header: []const u8) AddCookieError!void {
    // Duplicate the header string so we use it.
    const h = try self.arena.allocator().dupe(u8, header);

    // Split the header into parts by ';'
    var parts = std.mem.splitScalar(u8, h, ';');

    // Extract name and value from the first part
    var name_value = std.mem.splitScalar(u8, parts.next() orelse return error.InvalidFormat, '=');
    const name = name_value.next() orelse return error.InvalidFormat;
    const value = name_value.next() orelse return error.InvalidFormat;

    // Default cookie values
    const host = try uri.getHostAlloc(self.arena.allocator());
    var cookie: Cookie = .{
        .domain = host.bytes,
        .include_subdomains = false,
        .path = "/",
        .secure = false,
        .expires_at = 0, // Session cookie by default
        .name = name,
        .value = value,
    };

    // Parse attributes
    while (parts.next()) |part| {
        var attrs = std.mem.splitScalar(u8, part, '=');

        var buffer: [32]u8 = undefined;
        const keyOrig = std.mem.trim(u8, attrs.next() orelse continue, " ");
        const key = std.ascii.lowerString(&buffer, keyOrig[0..@min(keyOrig.len, buffer.len)]);

        const val = std.mem.trim(u8, attrs.next() orelse "", " ");

        const attr = AttributeField.map.get(key) orelse continue; // Ignore unknown attributes
        switch (attr) {
            .Domain => {
                cookie.domain = val;
                cookie.include_subdomains = true;
            },
            .Expires => {
                if (cookie.expires_at != 0) continue; // Max-Age takes precedence over Expires, so ignore Expires if Max-Age is already set
                const instant = zeit.instantFromText(.rfc1123, val, &zeit.utc) catch return error.InvalidFormat;
                cookie.expires_at = instant.unixTimestamp();
            },
            .MaxAge => {
                const max_age = std.fmt.parseInt(i64, val, 10) catch return error.InvalidFormat;
                if (max_age <= 0) {
                    // Cookie expires immediately, so we can skip adding it to the jar
                    return;
                }
                const now = Io.Clock.real.now(io).toSeconds();
                cookie.expires_at = now + max_age;
            },
            .Path => {
                cookie.path = val;
            },
            .Secure => {
                cookie.secure = true;
            },
        }
    }

    // De-dupe the cookie by removing any existing cookie with the same name/domain/path
    for (0..self.cookies.items.len) |i| {
        if (std.mem.eql(u8, self.cookies.items[i].name, cookie.name) and
            std.mem.eql(u8, self.cookies.items[i].domain, cookie.domain) and
            std.mem.eql(u8, self.cookies.items[i].path, cookie.path))
        {
            _ = self.cookies.orderedRemove(i);
            break;
        }
    }

    try self.cookies.append(self.arena.allocator(), cookie);
}

test "addCookie" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/path");
    try jar.addCookie(std.testing.io, uri, "sessionId=abc123; Path=/v1; Secure");
    try jar.addCookie(std.testing.io, uri, "theme=light; Expires=Wed, 09 Jun 2021 10:18:14 GMT");

    try std.testing.expectEqual(jar.cookies.items.len, 2);
    try std.testing.expectEqualStrings(jar.cookies.items[0].name, "sessionId");
    try std.testing.expectEqualStrings(jar.cookies.items[0].value, "abc123");
    try std.testing.expectEqualStrings(jar.cookies.items[0].path, "/v1");
    try std.testing.expect(jar.cookies.items[0].secure);
    try std.testing.expectEqualStrings(jar.cookies.items[1].name, "theme");
    try std.testing.expectEqualStrings(jar.cookies.items[1].value, "light");
    try std.testing.expectEqualStrings(jar.cookies.items[1].path, "/");
    try std.testing.expect(!jar.cookies.items[1].secure);
    try std.testing.expectEqual(jar.cookies.items[1].expires_at, 1623233894);
}

test "cookieHeader" {
    var jar = CookieJar.init(std.testing.allocator);
    defer jar.deinit();

    const uri = try std.Uri.parse("https://example.com/path");
    try jar.addCookie(std.testing.io, uri, "sessionId=abc123; Path=/path; Secure");
    try jar.addCookie(std.testing.io, uri, "sessionId2=abc123; Path=/v1; Secure");
    try jar.addCookie(std.testing.io, uri, "theme=light; Max-Age=3600");
    try jar.addCookie(std.testing.io, uri, "theme2=light; Expires=Wed, 09 Jun 2021 10:18:14 GMT");

    const header = try jar.cookieHeader(std.testing.allocator, std.testing.io, uri);
    defer std.testing.allocator.free(header);
    try std.testing.expectEqualStrings(header, "sessionId=abc123; theme=light");
}
